Update Org2.yml

diff --git a/.github/workflows/Org2.yml b/.github/workflows/Org2.yml
--- a/.github/workflows/Org2.yml
+++ b/.github/workflows/Org2.yml
@@ -14,7 +14,7 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: '14'  # Adjust the Node.js version as needed
+          node-version: '14'
 
       - name: Install Heroku CLI and hub
         run: |
@@ -49,7 +49,10 @@ jobs:
             PR_BODY="This pull request was automatically generated to trigger Heroku to check logs.🚀\n🌎 [View Site](https://$HEROKU_APP_NAME.herokuapp.com/)"
 
             echo "Attempting to create a pull request..."
-            hub pull-request -m "$PR_TITLE" -b main -h github-actions -m "$PR_BODY" || { echo "Error creating pull request"; exit 1; }
+            if ! hub pull-request -m "$PR_TITLE" -b main -h github-actions -m "$PR_BODY"; then
+              echo "Error creating pull request"
+              exit 1
+            fi
 
             echo "Pull request created successfully."
           else
